name: Docker Compose Workflow

on:
  push:
    branches:
      - main

jobs:
  docker-compose-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Docker Compose Action
      uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "./docker-compose.yml"

    - name: Archive output as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: output-artifact
        path: ./output/*
